name: locket_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  camera: ^0.11.2
  chewie: ^1.13.0
  flutter:
    sdk: flutter
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  uuid: ^4.5.1
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/video1.mp4
    - assets/videos/video2.mp4
    - assets/videos/video3.mp4
